Fix bash startup files to work
We never finished the startup files for Bash. Fix them to work by
loading `env/*` directory environment variables, optimize them to use
the cached plugin load order, and add support for *.local startup files.

diff --git a/lib/shells/bash/bashrc b/lib/shells/bash/bashrc
--- a/lib/shells/bash/bashrc
+++ b/lib/shells/bash/bashrc
@@ -5,13 +5,15 @@
 #
 # Do not make changes to this file -- use Dot plugins!
 
-if [ ! -L "$0" ]; then
-  echo "ERROR: $0 must be a symlink to lib/shells/bash/bashrc in the Dot framework"
+__file__="$HOME/.bashrc"
+
+if [ ! -L "$__file__" ]; then
+  echo "ERROR: $__file__ must be a symlink to lib/shells/bash/bashrc in the Dot framework"
   echo "ERROR: You should not execute or source this script directly!"
   echo "ERROR: Skipping initialization of Dot"
 else
-  export DOT_FRAMEWORK_DIR="$(cd "$(dirname "$(dirname "$(dirname "$(dirname "$(readlink "$0")")")")")" && pwd)"
-  export DOT_HOME="$(dirname "$(readlink "$DOT_FRAMEWORK_DIR")")"
+  export DOT_FRAMEWORK_DIR="$(cd "$(dirname "$(dirname "$(dirname "$(dirname "$(readlink "$__file__")")")")")" && pwd)"
+  export DOT_HOME="$(dirname "$DOT_FRAMEWORK_DIR")"
 
   export DOT_SHELL=bash
   export DOT_BACKUPS_DIR="$DOT_HOME/.backups"
@@ -23,19 +25,18 @@ else
 
   source "$DOT_FRAMEWORK_DIR/lib/shells/bash/load_env"
 
-  for plugin in $(dot::plugins::dependency_order); do
-    if ! dot::plugin::platform_supported "$plugin"; then
-      continue
-    fi
+  # Use cached load order created during installation
+  DOT_PLUGINS_DEPENDENCY_ORDER=($(cat "$DOT_HOME/.cache/plugin_load_order"))
 
+  for plugin in ${DOT_PLUGINS_DEPENDENCY_ORDER[@]}; do
     # Define variable so plugin's interactive shell script can use it for convenience
     DOT_PLUGIN_DIR="$DOT_PLUGINS_DIR/$plugin"
 
     if ! shopt -q login_shell; then
       # Skip if login shell since we already did it in bash_login
 
-      # Load any environment variables defined in relevant `env` directories
-      for env_path in "$DOT_PLUGIN_DIR/env"{,/setup{,/install}}"/"*(N); do
+      # Load any environment variables defined in `env` directory
+      for env_path in "$DOT_PLUGIN_DIR/env/"*; do
         if [ -f "$env_path" ]; then
           if ! load_env "$env_path"; then
             echo "ERROR: Failed to load environment variables for plugin $plugin. Halting"
@@ -45,10 +46,24 @@ else
       done
     fi
 
-    for script in "$DOT_PLUGIN_DIR/lib/interactive/"*".${DOT_SHELL}"; do
+    # Load any environment variables defined for interactive shells
+    for env_path in "$DOT_PLUGIN_DIR/env/interactive/"*; do
+      if [ -f "$env_path" ]; then
+        if ! load_env "$env_path"; then
+          echo "ERROR: Failed to load environment variables $env_path for plugin $plugin. Halting"
+          exit 1
+        fi
+      fi
+    done
+
+    for script in "$DOT_PLUGIN_DIR/lib/interactive/"*.bash; do
       if ! source "$script"; then
         echo "ERROR: Problem sourcing interactive script $script for plugin $plugin"
       fi
     done
   done
+
+  if [ -e "$HOME/.bashrc.local" ]; then
+    source "$HOME/.bashrc.local"
+  fi
 fi
