DRY up glob pattern expansion
This reverts commit c6dbb70cf6851c1504b522f3e9f97a1aae870f53 and
implements it in a different way to be more DRY.

It turns out that some `sh` implementations (e.g. `dash`) don't support
`{...}` glob patterns. This was causing us to fail in strange ways (e.g.
on a Chromebook).

Fix by avoiding those globs and using a `for` loop.

diff --git a/libexec/setup/install/dot::plugin::install b/libexec/setup/install/dot::plugin::install
--- a/libexec/setup/install/dot::plugin::install
+++ b/libexec/setup/install/dot::plugin::install
@@ -8,22 +8,26 @@ set -o nounset
 plugin_name="$1"
 export DOT_PLUGIN_DIR="$DOT_PLUGINS_DIR/$plugin_name"
 
-for bin in "$DOT_PLUGIN_DIR/bin/"* "$DOT_PLUGIN_DIR/libexec/"*; do
-  if [ ! -d "$bin" ] && [ -x "$bin" ]; then
-    ln -fs "$bin" "$DOT_PATH_DIR/$(basename $bin)"
-  fi
+for sub_dir in bin libexec; do
+  for bin in "$DOT_PLUGIN_DIR/$sub_dir/"*; do
+    if [ ! -d "$bin" ] && [ -x "$bin" ]; then
+      ln -fs "$bin" "$DOT_PATH_DIR/$(basename $bin)"
+    fi
+  done
 done
 
-for install_script_path in "$DOT_PLUGIN_DIR/setup/"* "$DOT_PLUGIN_DIR/setup/install/"*; do
-  if [ -f "$install_script_path" ]; then
+for sub_dir in setup setup/install; do
+  for install_script_path in "$DOT_PLUGIN_DIR/$sub_dir/"*; do
+    if [ -f "$install_script_path" ]; then
 
-    if [ -x "$install_script_path" ]; then
-      "$install_script_path"
-    fi
+      if [ -x "$install_script_path" ]; then
+        "$install_script_path"
+      fi
 
-    if [ ! $? -eq 0 ]; then
-      echo "ERROR: Problem occurred installing $plugin_name"
-      exit 1
+      if [ ! $? -eq 0 ]; then
+        echo "ERROR: Problem occurred installing $plugin_name"
+        exit 1
+      fi
     fi
-  fi
+  done
 done
diff --git a/libexec/setup/install/dot::plugins::install b/libexec/setup/install/dot::plugins::install
--- a/libexec/setup/install/dot::plugins::install
+++ b/libexec/setup/install/dot::plugins::install
@@ -14,20 +14,24 @@ for plugin in "$@"; do
 
   # Add anything in `libexec` directories to PATH so they can be executed by
   # this plugin or other dependent plugins during install
-  for libexec_path in "$plugin_dir/libexec" "$plugin_dir/libexec/setup" "$plugin_dir/libexec/setup/install"; do
-    if [ -d "$libexec_path" ]; then
-      export PATH="$libexec_path:$PATH"
-    fi
+  for sub_dir in libexec libexec/setup libexec/setup/install; do
+    for libexec_path in "$plugin_dir/$sub_dir"; do
+      if [ -d "$libexec_path" ]; then
+        export PATH="$libexec_path:$PATH"
+      fi
+    done
   done
 
   # Load any environment variables defined in relevant `env` directories
-  for env_path in "$plugin_dir/env/"* "$plugin_dir/env/setup/"* "$plugin_dir/env/setup/install/"*; do
-    if [ -f "$env_path" ]; then
-      if ! load_env "$env_path"; then
-        echo "ERROR: Failed to load environment variables for plugin $plugin. Halting"
-        exit 1
+  for sub_dir in env env/setup env/setup/install; do
+    for env_path in "$plugin_dir/$sub_dir/"*; do
+      if [ -f "$env_path" ]; then
+        if ! load_env "$env_path"; then
+          echo "ERROR: Failed to load environment variables for plugin $plugin. Halting"
+          exit 1
+        fi
       fi
-    fi
+    done
   done
 
   if ! dot::plugin::install "$plugin"; then
diff --git a/libexec/setup/uninstall/dot::plugin::uninstall b/libexec/setup/uninstall/dot::plugin::uninstall
--- a/libexec/setup/uninstall/dot::plugin::uninstall
+++ b/libexec/setup/uninstall/dot::plugin::uninstall
@@ -8,17 +8,19 @@ set -o nounset
 plugin_name="$1"
 plugin_dir="$DOT_PLUGINS_DIR/$plugin_name"
 
-for uninstall_script_path in "$plugin_dir/setup/"* "$plugin_dir/setup/uninstall/"*; do
-  if [ -f "$uninstall_script_path" ]; then
-    export DOT_PLUGIN_DIR="$plugin_dir"
+for sub_dir in setup setup/uninstall; do
+  for uninstall_script_path in "$plugin_dir/$sub_dir/"*; do
+    if [ -f "$uninstall_script_path" ]; then
+      export DOT_PLUGIN_DIR="$plugin_dir"
 
-    if [ -x "$uninstall_script_path" ]; then
-      "$uninstall_script_path"
-    fi
+      if [ -x "$uninstall_script_path" ]; then
+        "$uninstall_script_path"
+      fi
 
-    if [ ! $? -eq 0 ]; then
-      echo "ERROR: Problem occurred uninstalling $plugin_name"
-      exit 1
+      if [ ! $? -eq 0 ]; then
+        echo "ERROR: Problem occurred uninstalling $plugin_name"
+        exit 1
+      fi
     fi
-  fi
+  done
 done
